name: Build and Release Resume

on:
  push:
    branches: [ "master" ]
  release:
    types: [ published ]

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build the LaTeX resume using a modern GitHub Action
      - name: LaTeX Action
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv-lt.tex
          extra_packages: texlive-fonts-extra bibentry natbib cochineal cabin inconsolata  # Added font packages
          args: -pdf -file-line-error -interaction=nonstopmode
          latexmk_use_lualatex: true  # Use LuaLaTeX for fontspec support

      # Debug step: Show LaTeX logs if compilation fails
      - name: Show LaTeX logs on failure
        if: failure()
        run: |
          cat cv-lt.log || echo "Log file not found."

      # Upload artifact on push to master
      - name: Upload a Build Artifact
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4.4.3
        with:
          name: cv-lt.pdf
          path: cv-lt.pdf

      # Upload to GitHub Release if triggered by a release event
      - name: Upload resume to GitHub Release
        if: github.event_name == 'release'
        run: |
          gh release upload ${{ github.event.release.tag_name }} cv-lt.pdf
          gh release upload ${{ github.event.release.tag_name }} cv-lt.tex
        env:
          GH_TOKEN: ${{ github.token }}

      # Prepare files for GitHub Pages deployment during release
      - name: Move files for GitHub Pages
        if: github.event_name == 'release'
        run: |
          mkdir -p ../gh-pages
          mv cv-lt.pdf ../gh-pages/resume.pdf
          cp index.html ../gh-pages

      # Deploy to GitHub Pages during release
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'release'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ../gh-pages