# This is a basic workflow to help you get started with Actions

name: build resume on push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build the LaTeX resume using a gihub action
      - name: LaTeX Action
        uses: fudan-mse/latex-action@v0.0.1
        with:
          root_file: resume.tex
          # working_directory: # optional
          # compiler: # optional, default is latexmk
          # args: # optional, default is -pdf -file-line-error -interaction=nonstopmode
          # extra_packages: # optional
          # extra_system_packages: # optional
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: resume.pdf
          path: resume.pdf
